### ISSUE TITLE
A question about SARGCN 

### ISSUE THREAD

**Issue by striderdu** [JiapengWu/TeMP#13]
Hi, Jiapeng, thanks for released code. I want to know some detail about SARGCN.
https://github.com/JiapengWu/TeMP/blob/53e90c1e337615cfaa91c2cbfb21e2ed53842104/models/SelfAttentionRGCN.py#L97-L102
As above, update_time_diff_hist_embeddings does not return anything so that attn_mask and hist_embeddings will not be updated. This may impact the output of self attention module. I hope you can answer my doubts. Thanks a lot!

**Comment by ljn0320** [comment]
> Hi, Jiapeng, thanks for released code. I want to know some detail about SARGCN.
> 
> https://github.com/JiapengWu/TeMP/blob/53e90c1e337615cfaa91c2cbfb21e2ed53842104/models/SelfAttentionRGCN.py#L97-L102
> 
> 
> As above, update_time_diff_hist_embeddings does not return anything so that attn_mask and hist_embeddings will not be updated. This may impact the output of self attention module. I hope you can answer my doubts. Thanks a lot!

Hello, there are some problems when I configure the environment. Is your environment configured according to readme? My dgl can't find the version 0.4.1, and then there are many errors. What version is your dgl？thanks！！

**Comment by striderdu** [comment]
> > Hi, Jiapeng, thanks for released code. I want to know some detail about SARGCN.
> > https://github.com/JiapengWu/TeMP/blob/53e90c1e337615cfaa91c2cbfb21e2ed53842104/models/SelfAttentionRGCN.py#L97-L102
> > 
> > As above, update_time_diff_hist_embeddings does not return anything so that attn_mask and hist_embeddings will not be updated. This may impact the output of self attention module. I hope you can answer my doubts. Thanks a lot!
> 
> Hello, there are some problems when I configure the environment. Is your environment configured according to readme? My dgl can't find the version 0.4.1, and then there are many errors. What version is your dgl？thanks！！

 Hi, @ljn0320 . My dgl version is 0.6.1. To do this, I modified some code that create DGLGraph objects. Hope my reply can help you.

**Comment by JiapengWu** [comment]
Sorry, I have graduated and no longer have the energy to maintain/update this project.

**Comment by JiapengWu** [comment]
There needs to be some adjustment to the implementation to adapt to a higher version of DGL.

**Comment by striderdu** [comment]
> Sorry, I have graduated and no longer have the energy to maintain/update this project.

Okay, I got it. Thanks for your reply~

**Comment by ljn0320** [comment]
> > > Hi, Jiapeng, thanks for released code. I want to know some detail about SARGCN.
> > > https://github.com/JiapengWu/TeMP/blob/53e90c1e337615cfaa91c2cbfb21e2ed53842104/models/SelfAttentionRGCN.py#L97-L102
> > > 
> > > As above, update_time_diff_hist_embeddings does not return anything so that attn_mask and hist_embeddings will not be updated. This may impact the output of self attention module. I hope you can answer my doubts. Thanks a lot!
> > 
> > 
> > Hello, there are some problems when I configure the environment. Is your environment configured according to readme? My dgl can't find the version 0.4.1, and then there are many errors. What version is your dgl？thanks！！
> 
> Hi, @ljn0320 . My dgl version is 0.6.1. To do this, I modified some code that create DGLGraph objects. Hope my reply can help you.

Thank you very much for your reply, which has solved my doubts. I am now working on my graduation project. Can you share your code? Thanks again!
